# Generated by Django 4.1.3 on 2023-02-10 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_orders_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='dicount',
        ),
        migrations.AddField(
            model_name='offers',
            name='discount',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offers',
            name='end_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='offers',
            name='start_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='expected_deliverydate',
            field=models.DateField(default=datetime.date(2023, 2, 15)),
        ),
    ]
